accessing
exception
  ^ self theStack exception